require:
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.4
  DisplayStyleGuide: true
  DisplayCopNames: true

#################
# [i] Overrides #
#################

Style/CollectionMethods:
  # Mapping from undesired method to desired_method
  # e.g. to use `detect` over `find`:
  #
  # CollectionMethods:
  #   PreferredMethods:
  #     find: detect
  PreferredMethods:
    collect: 'map'
    reduce: 'inject'
    find: 'detect'
    each_with_index: 'each.with_index'

# Align ends correctly.
Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/BlockAlignment:
  EnforcedStyleAlignWith: start_of_block

Layout/AlignHash:
  Enabled: true
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Metrics/LineLength:
  Max: 125
  Exclude:
    - examples/**/*
    - spec/**/*

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/AbcSize:
  Max: 18

#################
# Disabled cops #
#################
Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

#################
# Modified cops #
#################

Naming/FileName:
  Enabled: true
  Exclude:
    - gemfiles/*

Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/GuardClause:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*
